export default {
    products: [
        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },

        {
            _id: '1',
            name: 'Slim shirt',
            category: 'Shirts',
            image: '/images/kinky.jpeg',
            price: 70,
            brand: "Soap",
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};